# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false
org.gradle.cache.cleanup = false

# Mod Properties
maven_group = me.aleksilassila
mod_id = litematica-printer
mod_name = Litematica Printer
mod_file_name = litematica-printer

# Mod Version
mod_version = 3.2.2

# Dependencies (malilib / litematica)
malilib_version = 0.29.0
litematica_version = 0.28.4

# Minecraft, Fabric Loader and API and mappings versions
minecraft_version_out = 26.2
minecraft_version = 26.2

fabric_loader_version = 0.19.3
mod_menu_version = 20.0.0-beta.2
fabric_api_version = 0.152.1+26.2
